import "@radix-ui/themes/styles.css";
import "./globals.css";

import { Inter } from "next/font/google";

import { Container, Theme } from "@radix-ui/themes";

import AuthProvider from "./auth/Provider";
import NavBar from "./NavBar";

import type { Metadata } from "next";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>
          <Theme accentColor="violet">
            <NavBar />
            <main className="px-4">
              <Container>{children}</Container>
            </main>
            {/* <ThemePanel /> */}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
