import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";

import { Inter } from "next/font/google";

import { Theme, ThemePanel } from "@radix-ui/themes";

import NavBar from "./NavBar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Theme accentColor="violet">
          <NavBar />
          <main>{children}</main>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
